#!/bin/bash
#PBS -q default
#PBS -N Job_SumMatrix
##serial jobs: only 1 processor core is requested
#PBS -l select=1:mem=4gb:ncpus=2
#PBS -l walltime=08:00:00
##replace "x-ccast-prj" below with "x-ccast-prj-[your sponsor's project group]"
#PBS -W group_list=x-ccast-prj-luliu
#
#
cd $PBS_O_WORKDIR
#
##change the input filename if needed
##python ../src/preprocessing/GetMaxSumMatrix.py --analyze-dir "/gpfs1/scratch/chanaka.cooray/jobs/work/output-1M/EdgesBin" --metadata "../metadata" --bin-size "1M" --cell-type "1CDX1" >> ../analyze-1M/Max1CDX1_1M.txt
##python ../src/preprocessing/GetMaxSumMatrix.py --analyze-dir "/gpfs1/scratch/chanaka.cooray/jobs/work/output-1M/EdgesBin" --metadata "../metadata" --bin-size "1M" --cell-type "1CDX2" >> ../analyze-1M/Max1CDX2_1M.txt
##python ../src/preprocessing/GetMaxSumMatrix.py --analyze-dir "/gpfs1/scratch/chanaka.cooray/jobs/work/output-1M/EdgesBin" --metadata "../metadata" --bin-size "1M" --cell-type "1CDX3" >> ../analyze-1M/Max1CDX3_1M.txt
##python ../src/preprocessing/GetMaxSumMatrix.py --analyze-dir "/gpfs1/scratch/chanaka.cooray/jobs/work/output-1M/EdgesBin" --metadata "../metadata" --bin-size "1M" --cell-type "1CDX4" >> ../analyze-1M/Max1CDX4_1M.txt

python ../src/preprocessing/GetMaxSumMatrix.py --analyze-dir "/gpfs1/scratch/chanaka.cooray/jobs/work/output-500k/shift-100k/EdgesBin" --metadata "../metadata" --bin-size "500k" --cell-type "1CDX1" --shift 100k >> ../analyze-500k/SumMatrix/shift-100k/Max1CDX1_500k_shift_100k.txt
python ../src/preprocessing/GetMaxSumMatrix.py --analyze-dir "/gpfs1/scratch/chanaka.cooray/jobs/work/output-500k/shift-100k/EdgesBin" --metadata "../metadata" --bin-size "500k" --cell-type "1CDX2" --shift 100k >> ../analyze-500k/SumMatrix/shift-100k/Max1CDX2_500k_shift_100k.txt
python ../src/preprocessing/GetMaxSumMatrix.py --analyze-dir "/gpfs1/scratch/chanaka.cooray/jobs/work/output-500k/shift-100k/EdgesBin" --metadata "../metadata" --bin-size "500k" --cell-type "1CDX3" --shift 100k >> ../analyze-500k/SumMatrix/shift-100k/Max1CDX3_500k_shift_100k.txt
python ../src/preprocessing/GetMaxSumMatrix.py --analyze-dir "/gpfs1/scratch/chanaka.cooray/jobs/work/output-500k/shift-100k/EdgesBin" --metadata "../metadata" --bin-size "500k" --cell-type "1CDX4" --shift 100k >> ../analyze-500k/SumMatrix/shift-100k/Max1CDX4_500k_shift_100k.txt

python ../src/preprocessing/GetMaxSumMatrix.py --analyze-dir "/gpfs1/scratch/chanaka.cooray/jobs/work/output-500k/shift-200k/EdgesBin" --metadata "../metadata" --bin-size "500k" --cell-type "1CDX1" --shift 200k >> ../analyze-500k/SumMatrix/shift-200k/Max1CDX1_500k_shift_200k.txt
python ../src/preprocessing/GetMaxSumMatrix.py --analyze-dir "/gpfs1/scratch/chanaka.cooray/jobs/work/output-500k/shift-200k/EdgesBin" --metadata "../metadata" --bin-size "500k" --cell-type "1CDX2" --shift 200k >> ../analyze-500k/SumMatrix/shift-200k/Max1CDX2_500k_shift_200k.txt
python ../src/preprocessing/GetMaxSumMatrix.py --analyze-dir "/gpfs1/scratch/chanaka.cooray/jobs/work/output-500k/shift-200k/EdgesBin" --metadata "../metadata" --bin-size "500k" --cell-type "1CDX3" --shift 200k >> ../analyze-500k/SumMatrix/shift-200k/Max1CDX3_500k_shift_200k.txt
python ../src/preprocessing/GetMaxSumMatrix.py --analyze-dir "/gpfs1/scratch/chanaka.cooray/jobs/work/output-500k/shift-200k/EdgesBin" --metadata "../metadata" --bin-size "500k" --cell-type "1CDX4" --shift 200k >> ../analyze-500k/SumMatrix/shift-200k/Max1CDX4_500k_shift_200k.txt

python ../src/preprocessing/GetMaxSumMatrix.py --analyze-dir "/gpfs1/scratch/chanaka.cooray/jobs/work/output-500k/shift-300k/EdgesBin" --metadata "../metadata" --bin-size "500k" --cell-type "1CDX1" --shift 300k >> ../analyze-500k/SumMatrix/shift-300k/Max1CDX1_500k_shift_300k.txt
python ../src/preprocessing/GetMaxSumMatrix.py --analyze-dir "/gpfs1/scratch/chanaka.cooray/jobs/work/output-500k/shift-300k/EdgesBin" --metadata "../metadata" --bin-size "500k" --cell-type "1CDX2" --shift 300k >> ../analyze-500k/SumMatrix/shift-300k/Max1CDX2_500k_shift_300k.txt
python ../src/preprocessing/GetMaxSumMatrix.py --analyze-dir "/gpfs1/scratch/chanaka.cooray/jobs/work/output-500k/shift-300k/EdgesBin" --metadata "../metadata" --bin-size "500k" --cell-type "1CDX3" --shift 300k >> ../analyze-500k/SumMatrix/shift-300k/Max1CDX3_500k_shift_300k.txt
python ../src/preprocessing/GetMaxSumMatrix.py --analyze-dir "/gpfs1/scratch/chanaka.cooray/jobs/work/output-500k/shift-300k/EdgesBin" --metadata "../metadata" --bin-size "500k" --cell-type "1CDX4" --shift 300k >> ../analyze-500k/SumMatrix/shift-300k/Max1CDX4_500k_shift_300k.txt

python ../src/preprocessing/GetMaxSumMatrix.py --analyze-dir "/gpfs1/scratch/chanaka.cooray/jobs/work/output-500k/shift-400k/EdgesBin" --metadata "../metadata" --bin-size "500k" --cell-type "1CDX1" --shift 400k >> ../analyze-500k/SumMatrix/shift-400k/Max1CDX1_500k_shift_400k.txt
python ../src/preprocessing/GetMaxSumMatrix.py --analyze-dir "/gpfs1/scratch/chanaka.cooray/jobs/work/output-500k/shift-400k/EdgesBin" --metadata "../metadata" --bin-size "500k" --cell-type "1CDX2" --shift 400k >> ../analyze-500k/SumMatrix/shift-400k/Max1CDX2_500k_shift_400k.txt
python ../src/preprocessing/GetMaxSumMatrix.py --analyze-dir "/gpfs1/scratch/chanaka.cooray/jobs/work/output-500k/shift-400k/EdgesBin" --metadata "../metadata" --bin-size "500k" --cell-type "1CDX3" --shift 400k >> ../analyze-500k/SumMatrix/shift-400k/Max1CDX3_500k_shift_400k.txt
python ../src/preprocessing/GetMaxSumMatrix.py --analyze-dir "/gpfs1/scratch/chanaka.cooray/jobs/work/output-500k/shift-400k/EdgesBin" --metadata "../metadata" --bin-size "500k" --cell-type "1CDX4" --shift 400k >> ../analyze-500k/SumMatrix/shift-400k/Max1CDX4_500k_shift_400k.txt


#
exit 0
