#!/bin/bash
#PBS -q default
#PBS -N Job_AnalyzeTool_oocyte_NSN
##serial jobs: only 1 processor core is requested
#PBS -l select=1:mem=8gb:ncpus=4
#PBS -l walltime=72:00:00
##replace "x-ccast-prj" below with "x-ccast-prj-[your sponsor's project group]"
#PBS -W group_list=x-ccast-prj-luliu
#
#
cd $PBS_O_WORKDIR
#

python ../../src/tool/AnalyzeTool.py --data "/gpfs1/scratch/chanaka.cooray/jobs/work/preprocessed-data/oocyte_NSN/oocyte_NSN" --bin-size "1M" --config-file "../../metadata/chrom_sizes.txt" --output "../../output/tool-output-newdata/oocyte_NSN/oocyte_NSN/1M"
python ../../src/tool/AnalyzeTool.py --data "/gpfs1/scratch/chanaka.cooray/jobs/work/preprocessed-data/oocyte_NSN/oocyte_NSN" --bin-size "500k" --config-file "../../metadata/chrom_sizes.txt" --output "../../output/tool-output-newdata/oocyte_NSN/oocyte_NSN/500k"
python ../../src/tool/AnalyzeTool.py --data "/gpfs1/scratch/chanaka.cooray/jobs/work/preprocessed-data/oocyte_NSN/oocyte_NSN" --bin-size "40k" --config-file "../../metadata/chrom_sizes.txt" --output "../../output/tool-output-newdata/oocyte_NSN/oocyte_NSN/40k"
python ../../src/tool/AnalyzeTool.py --data "/gpfs1/scratch/chanaka.cooray/jobs/work/preprocessed-data/oocyte_NSN/oocyte_NSN" --bin-size "200k" --config-file "../../metadata/chrom_sizes.txt" --output "../../output/tool-output-newdata/oocyte_NSN/oocyte_NSN/200k"

#
exit 0
